version: '3.8'
services:
  server:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
      - "./src:/var/www/html"

  php:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - "./src:/var/www/html"

  mysql:
    image: mysql:5.7
    env_file:
      - ./env/mysql.env

  # run first
  composer:
    image: composer:latest
    working_dir: /var/www/html
    volumes:
      - ./src/:/var/www/html